/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
    './src/layouts/**/*.{js,jsx,ts,tsx}',
    './src/wrappers/**/*.{js,jsx,ts,tsx}',
    './src/app.{ts,tsx}',
  ],
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#37485f',
        'inverse-on-surface': '#27313f',
        'secondary-fixed': '#28fedc',
        'surface-variant': '#2c3544',
        'secondary-container': '#00f2d1',
        'on-secondary-fixed-variant': '#005144',
        'on-primary-fixed-variant': '#005143',
        'on-primary-fixed': '#00201a',
        background: '#0a1421',
        'on-surface': '#d9e3f6',
        'on-background': '#d9e3f6',
        'inverse-primary': '#006b5a',
        'surface-dim': '#0a1421',
        'surface-container-highest': '#2c3544',
        'on-tertiary-fixed': '#0a1c31',
        surface: '#0a1421',
        'tertiary-container': '#bccde9',
        'on-primary': '#00382e',
        'primary-fixed-dim': '#00dfbe',
        'secondary-fixed-dim': '#00dfc1',
        'on-secondary-container': '#006a5a',
        secondary: '#c7fff0',
        'error-container': '#93000a',
        'primary-fixed': '#42fdda',
        primary: '#70ffe0',
        error: '#ffb4ab',
        'outline-variant': '#3b4a45',
        'on-tertiary-container': '#46576f',
        'on-surface-variant': '#b9cac4',
        'tertiary-fixed-dim': '#b6c8e4',
        'on-secondary': '#00382f',
        'surface-container-low': '#121c29',
        'on-tertiary': '#203147',
        'surface-container': '#16202e',
        'surface-container-lowest': '#050f1b',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#006152',
        tertiary: '#dce9ff',
        'surface-container-high': '#212a38',
        'primary-container': '#00e5c3',
        'surface-tint': '#00dfbe',
        'on-error': '#690005',
        'tertiary-fixed': '#d3e3ff',
        outline: '#84948f',
        'on-secondary-fixed': '#00201a',
        'surface-bright': '#303a48',
        'inverse-surface': '#d9e3f6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'stack-lg': '32px',
        'stack-xs': '4px',
        'margin-mobile': '16px',
        'stack-xl': '64px',
        'container-max': '1280px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'headline-lg': ['Sora'],
        'headline-md': ['Sora'],
        'headline-lg-mobile': ['Sora'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-xl': ['Sora'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'label-md': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
};
