// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import AppstoreAddOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreAddOutlined';
import ToolOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ToolOutlined';
import DollarOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DollarOutlined';
import TeamOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import NotificationOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/NotificationOutlined';
import PieChartOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/PieChartOutlined';
import ProfileOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import ControlOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ControlOutlined';
import QuestionCircleOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/QuestionCircleOutlined';
import UserOutlined from 'C:/Users/DUC TRUONG/Downloads/RIPT1307-02-2026-Nhom-11-KTHP/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { DashboardOutlined, AppstoreAddOutlined, ToolOutlined, DollarOutlined, TeamOutlined, NotificationOutlined, PieChartOutlined, ProfileOutlined, ControlOutlined, QuestionCircleOutlined, UserOutlined };
